const SOCIAL_LINKS = {
  github: "https://github.com/Kraverse",
  linkedin: "https://linkedin.com/in/kraverse",
  email: "mailto:kk1dgca@gmail.com",
};

const PROJECTS = [
  {
    title: "DhobiXpert",
    category: "Full Stack · Production Website",
    tags: ["Full Stack", "Production"],
    status: "Live & Production Ready",
    live: true,
    description: "Production-ready digital platform for a modern laundry service.",
    tech: ["Next.js", "React", "Tailwind CSS"],
    link: "https://dhobyexpert.vercel.app/",
    github: "https://github.com/Kraverse",
    visual: "dhobixpert",
    overview: "A complete digital experience for a modern laundry service — built as a real, deployed product rather than a demo.",
    problem: "Small service businesses often have no online presence: customers can't see services, pricing or request a pickup without calling.",
    solution: "A polished, responsive marketing and booking experience built with Next.js and deployed to production on Vercel.",
    aiComponents: "Modern web architecture with a component-driven Next.js codebase; designed so AI features can be layered in later.",
    features: ["Responsive Next.js frontend", "Service & pricing presentation", "Production deployment on Vercel", "Component-driven codebase"],
  },
  {
    title: "MedRec AI",
    category: "Healthcare AI · Generative AI",
    tags: ["Generative AI", "AI / ML", "Healthcare"],
    status: "In Development",
    live: false,
    description: "Healthcare-focused AI application concept for assisting doctors with medical records and intelligent workflows.",
    tech: ["Python", "FastAPI", "LLMs", "Next.js", "AI APIs"],
    link: "https://github.com/Kraverse/medrec-ai",
    github: "https://github.com/Kraverse/medrec-ai",
    visual: "medrec",
    overview: "An AI-focused healthcare application designed around practical clinical workflows and doctor-facing productivity.",
    problem: "Healthcare professionals deal with large amounts of information and repetitive documentation during daily workflows.",
    solution: "A modern AI application architecture connecting a doctor-friendly interface with backend AI services.",
    aiComponents: "LLM integration, AI-assisted workflows, structured healthcare information handling and API-based AI services.",
    features: ["Doctor-focused workflow design", "AI-assisted information handling", "FastAPI backend architecture", "Modern web interface"],
  },
  {
    title: "HelpDesk AI",
    category: "Generative AI · RAG",
    tags: ["Generative AI", "AI / ML", "RAG"],
    status: "Buildable / In Development",
    live: false,
    description: "Enterprise-style AI assistant that retrieves relevant information from a knowledge base and generates contextual responses.",
    tech: ["Python", "RAG", "LangChain", "LLM"],
    link: "https://github.com/Kraverse/HelpDesk-AI-Enterprise-RAG-Assistant",
    github: "https://github.com/Kraverse/HelpDesk-AI-Enterprise-RAG-Assistant",
    visual: "helpdesk",
    overview: "A retrieval-augmented generation assistant that grounds LLM answers in a private knowledge base.",
    problem: "Generic LLMs can struggle with organization-specific questions because they lack access to internal documentation.",
    solution: "A RAG pipeline where documents are processed, relevant passages are retrieved at query time, and responses are generated from that context.",
    aiComponents: "Retrieval-Augmented Generation, LangChain orchestration, semantic retrieval, prompt engineering and LLM response generation.",
    features: ["Document ingestion & chunking", "Semantic retrieval", "Context-grounded responses", "Interactive AI interface"],
  },
  {
    title: "ContextBridge AI",
    category: "AI Productivity Tool",
    tags: ["Generative AI", "AI / ML", "Productivity"],
    status: "Experimental",
    live: false,
    description: "AI context transfer tool designed to move useful conversation context between different AI assistants.",
    tech: ["JavaScript", "Chrome Extension", "AI APIs"],
    link: "https://github.com/Kraverse/ContextBridge-AI",
    github: "https://github.com/Kraverse/ContextBridge-AI",
    visual: "context",
    overview: "A tooling experiment for carrying useful conversation context across AI assistants without restarting from zero.",
    problem: "Switching between AI assistants often means re-explaining the same task and losing accumulated context.",
    solution: "A modular context-transfer workflow that packages conversation information into a form usable by different AI assistants.",
    aiComponents: "AI API integration, context structuring and prompt-friendly context serialization.",
    features: ["Cross-assistant context transfer", "Chrome extension architecture", "Context extraction", "Extensible design"],
  },
  {
    title: "KraVoice",
    category: "AI · Speech & Transcription",
    tags: ["AI / ML", "Speech AI", "Python"],
    status: "Live Demo",
    live: true,
    description: "AI-powered audio transcription and media processing application for converting speech into usable text.",
    tech: ["Python", "Streamlit", "Whisper", "YouTube", "yt-dlp"],
    link: "https://kravoice.streamlit.app/",
    github: "https://github.com/Kraverse/KraVoice",
    visual: "kravoice",
    overview: "A practical speech-to-text application supporting uploaded audio and online media workflows.",
    problem: "Transcribing audio and extracting usable text from online media can require several disconnected tools.",
    solution: "A simple Streamlit interface that brings transcription, media processing and downloadable text formats into one workflow.",
    aiComponents: "Whisper-based speech recognition and AI-assisted transcription workflows.",
    features: ["Whisper model selection", "Audio/video transcription", "YouTube media support", "TXT, SRT & VTT output"],
  },
  {
    title: "ChurnIQ-ML",
    category: "Machine Learning",
    tags: ["AI / ML", "Machine Learning"],
    status: "Completed",
    live: false,
    description: "Machine learning project focused on predicting customer churn using data-driven modeling and evaluation.",
    tech: ["Python", "scikit-learn", "Pandas", "Machine Learning"],
    link: "https://github.com/Kraverse/ChurnIQ-ML",
    github: "https://github.com/Kraverse/ChurnIQ-ML",
    visual: "churniq",
    overview: "An end-to-end ML workflow that predicts which customers are likely to churn, from data preparation to model evaluation.",
    problem: "Businesses need to identify customers who may leave so retention efforts can be targeted effectively.",
    solution: "A supervised classification workflow covering data preparation, feature handling, model training and evaluation.",
    aiComponents: "Supervised classification, feature engineering, model evaluation and scikit-learn workflows.",
    features: ["Data cleaning & analysis", "Feature engineering", "Model training & comparison", "ROC-AUC and accuracy evaluation"],
  },
  {
    title: "KraverseAI",
    category: "Generative AI · Personal Assistant",
    tags: ["Generative AI", "LLM", "AI Assistant"],
    status: "Prototype",
    live: false,
    description: "Personal AI assistant concept designed to answer questions about my projects, skills and technical work.",
    tech: ["Python", "LLM APIs", "AI Assistant"],
    link: "https://github.com/Kraverse/KraverseAI",
    github: "https://github.com/Kraverse/KraverseAI",
    visual: "kraverseai",
    overview: "A portfolio-oriented AI assistant that provides conversational access to project and profile information.",
    problem: "Traditional portfolios require recruiters to manually browse multiple sections to understand a developer's work.",
    solution: "An AI assistant concept that provides a conversational way to explore project and professional information.",
    aiComponents: "LLM API integration, prompt design and structured project/profile context.",
    features: ["Project-aware assistant", "Conversational portfolio exploration", "LLM API integration", "Personal knowledge context"],
  },
  {
    title: "ChronosPulse AI",
    category: "Healthcare · AI Application",
    tags: ["AI / ML", "Healthcare", "Full Stack"],
    status: "Prototype",
    live: false,
    description: "Healthcare workflow application focused on triage, queue management and intelligent patient-flow assistance.",
    tech: ["Python", "FastAPI", "Next.js", "SQLite"],
    link: "https://github.com/Kraverse/ChronosPulse-AI",
    github: "https://github.com/Kraverse/ChronosPulse-AI",
    visual: "chronos",
    overview: "A healthcare workflow prototype exploring how software can support triage and patient queue management.",
    problem: "Busy healthcare environments need clear visibility into patient queues and prioritization.",
    solution: "A full-stack workflow prototype combining a modern frontend with a FastAPI backend and structured queue data.",
    aiComponents: "Intelligent triage and prioritization concepts within a healthcare workflow application.",
    features: ["Patient queue management", "Triage workflow", "FastAPI backend", "Next.js interface"],
  },
  {
    title: "AI PDF Chatbot",
    category: "Generative AI · RAG",
    tags: ["Generative AI", "RAG", "LangChain"],
    status: "Prototype",
    live: false,
    description: "Document question-answering experiment using retrieval and language models to interact with PDF content.",
    tech: ["Python", "LangChain", "LLM", "PDF Processing"],
    link: "https://github.com/Kraverse/ai-pdf-chatbot-langchain-main",
    github: "https://github.com/Kraverse/ai-pdf-chatbot-langchain-main",
    visual: "pdf",
    overview: "A focused RAG experiment for asking natural-language questions about PDF documents.",
    problem: "Finding specific information inside long documents manually can be slow and inconvenient.",
    solution: "A document-processing and retrieval workflow that lets users query PDF content using natural language.",
    aiComponents: "Document chunking, retrieval and LLM-based question answering.",
    features: ["PDF ingestion", "Semantic retrieval", "Natural-language questions", "Context-aware answers"],
  },
];

const FILTERS = ["All", "AI / ML", "Generative AI", "Healthcare", "Full Stack", "Production"];

const TECH_STACK = ["Python", "React", "Next.js", "FastAPI", "LangChain", "Supabase", "GitHub", "Vercel"];

const SKILL_GROUPS = [
  { group: "AI / ML", skills: ["Python", "Machine Learning", "Generative AI", "LLMs", "RAG", "LangChain", "Whisper"] },
  { group: "Frontend", skills: ["React", "Next.js", "JavaScript", "TypeScript", "Tailwind CSS", "Streamlit"] },
  { group: "Backend", skills: ["Python", "FastAPI", "REST APIs", "Node.js"] },
  { group: "Data / Infrastructure", skills: ["Supabase", "PostgreSQL", "MongoDB", "Git", "GitHub", "Vercel", "Render"] },
];

const LEARNING = [
  { title: "AI & Machine Learning", note: "Core concepts, modeling & evaluation" },
  { title: "Generative AI & LLM Applications", note: "Prompting, agents & AI products" },
  { title: "RAG Systems", note: "Retrieval-augmented generation pipelines" },
  { title: "Healthcare AI", note: "AI-assisted healthcare workflows" },
  { title: "Full-Stack AI Applications", note: "End-to-end intelligent products" },
  { title: "Production Deployment", note: "Shipping & maintaining real apps" },
];
